version: '3.8'

services:
  identity.api:
    image: identityapi
    build:
      context: .
      dockerfile: identity/Dockerfile
    ports:
      - "5028:8080"  
    depends_on:
      - db
      - redis
    environment:
      ConnectionStrings__Default: "Server=db;Database=AIdentity;User Id=sa;Password=P@ssw0rd;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      Redis__Enabled: "true"
      Redis__Hosts__0__Host: "redis"
      Redis__Hosts__0__Port: "6379"
      Redis__password: "getadmin"
    networks:
      - identity-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - identity-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "getadmin"]
    networks:
      - identity-network

volumes:
  sqlvolume:

networks:
  identity-network:
